START
dataType mc
###MVA Flags###
createMVATree 1
readMVA 0
isXZ 1
isH2Z 0
MVAnetwork BDTG
MVAxmlFile /home/gsaha/DelphesAnalysis/JobCards/BDT_WEIGHTS/XZ/TMVAClassification_BDTG.weights.xml
MVAxmlFile2 /home/gsaha/DelphesAnalysis/JobCards/BDT_WEIGHTS/H2Z/TMVAClassification_BDTG.weights.xml
mvaInputFile test_mvaIn.root
mvaOutputFile Signal_xmutau_Wlnu_mvaOut.root
CutOnMVAScorePlane 1
###############
lumiWtList xsec=0.029654 intLumi=300000 nevents=100000
histFile  test_hist.root
maxEvent -1
###############
#Cuts
muonCutList eta=2.4 pt=10. iso=0.15.
electronCutList pt=10. eta=2.5 iso=0.11.
tauCutList eta=2.5 pt=20. dz=0.2 muVeto=0.5 eleVeto=0.5 isol=0.5
jetCutList eta=4.7 pt=20 mindRlep=0.1 
photonCutList pt=2 eta=2.4 isol=1.8 dRmin=0.5 dRovEt2=0.012
evselCutList hLepPtMin=60 ZMassLow=60. ZMassHigh=120. maxJetPt=60. maxMET=200. minDRLP=0.2
#inputFiles
inputFile /home/gsaha/Data/SIGNALs/XZ_20_160/XZ_20_160_Yl_0.003_Yq_0.003_RootFiles/XZ_20_160_Yl_0.003_Yq_0.003_1.root
readGenInfo 0
dumpGenInfo 0
eventId 1 895751 20
END
