Tag: DL_MX_100_Final

Lumi: 300000

infiles:
  Signal :
    muta_lnu : [/home/gsaha/Work/Delphes_Analyses/Project_FCNC_TTbar/JobOutput_MX_100/results/Sig_Xmuta_0p01_Xct_0p01_Xuc_0p005_MX_100_MH_160_DL_BDTD_mvaIn.root, 0.00867, 700000, 'signal']
  Background :
    TTJets2L : [/home/gsaha/Work/Delphes_Analyses/Project_FCNC_TTbar/JobOutput_MX_60/results/Bkg_TTJets_DiLep_Set_New_DL_BDTD_mvaIn.root, 109.8, 10855428, 'TT + Jets']
    TTWJets  : [/home/gsaha/Work/Delphes_Analyses/Project_FCNC_TTbar/JobOutput_MX_60/results/Bkg_TTWJetsToLNu_DL_BDTD_mvaIn.root, 0.25, 4765526, 'TTV + Jets']
    TTZJets  : [/home/gsaha/Work/Delphes_Analyses/Project_FCNC_TTbar/JobOutput_MX_60/results/Bkg_TTZJetsToLL_DL_BDTD_mvaIn.root, 0.24, 2584012, 'TTV + Jets']
    #RestBackground:
    WZTo3LNu : [/home/gsaha/Work/Delphes_Analyses/Project_FCNC_TTbar/JobOutput_MX_60/results/Bkg_WZTo3LNu_012Jets_DL_BDTD_mvaIn.root, 2.273, 9947106, 'VV(V) + Jets']
    WZTo2L2Q : [/home/gsaha/Work/Delphes_Analyses/Project_FCNC_TTbar/JobOutput_MX_60/results/Bkg_WZTo2L2Q_012Jets_DL_BDTD_mvaIn.root, 4.504, 2477920, 'VV(V) + Jets']
    ZZTo4L   : [/home/gsaha/Work/Delphes_Analyses/Project_FCNC_TTbar/JobOutput_MX_60/results/Bkg_ZZTo4L_012Jets_DL_BDTD_mvaIn.root, 0.187, 2500000, 'VV(V) + Jets']
    WWW      : [/home/gsaha/Work/Delphes_Analyses/Project_FCNC_TTbar/JobOutput_MX_60/results/Bkg_WWW_DL_BDTD_mvaIn.root, 0.236, 240000, 'VV(V) + Jets']
    WWZ      : [/home/gsaha/Work/Delphes_Analyses/Project_FCNC_TTbar/JobOutput_MX_60/results/Bkg_WWZ_DL_BDTD_mvaIn.root, 0.189, 250000, 'VV(V) + Jets']
    WZZ      : [/home/gsaha/Work/Delphes_Analyses/Project_FCNC_TTbar/JobOutput_MX_60/results/Bkg_WZZ_DL_BDTD_mvaIn.root, 0.064, 246800, 'VV(V) + Jets']
    ZZZ      : [/home/gsaha/Work/Delphes_Analyses/Project_FCNC_TTbar/JobOutput_MX_60/results/Bkg_ZZZ_DL_BDTD_mvaIn.root, 0.016, 249237, 'VV(V) + Jets']
    TTWQQ    : [/home/gsaha/Work/Delphes_Analyses/Project_FCNC_TTbar/JobOutput_MX_60/results/Bkg_TTWToQQ_DL_BDTD_mvaIn.root, 0.074, 3900000, 'TTV + Jets']
    bbtata   : [/home/gsaha/Work/Delphes_Analyses/Project_FCNC_TTbar/JobOutput_MX_60/results/Bkg_bbtautau_DL_BDTD_mvaIn.root, 0.115, 4450000, 'Rares']

intree: EventsDL

features:
  - pt_tauh
  - met
  - pt_leadbj
  - pt_xlep
  - pt_wlep
  - vectorsumpt_xlep_wlep
  - dr_xlep_wlep
  - dphi_wlep_tauh
  - dphi_wlep_leadbj
  - ht_jets
  - dr_min_xlep_jets
  - dr_min_wlep_jets
  - dphi_xlep_tauh
  #- effectivemass
  - effectiveMass_t1
  - effectiveMass_t2
  - dr_min_jets
  - mt_wlep_met
  - dphi_tauh_leadbj
  - dphi_met_xlep
  - dphi_met_wlep
  - dphi_leadbj_leadlj
  - smin

UseNormForPlots : yes